// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Prisstyrning.Data;

#nullable disable

namespace Prisstyrning.Data.Migrations
{
    [DbContext(typeof(PrisstyrningDbContext))]
    partial class PrisstyrningDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Prisstyrning.Data.Entities.AdminRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("HasHangfireAccess")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.ToTable("AdminRoles");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.DaikinInstallation", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("DhwManagementPointEmbeddedId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("HeatingManagementPointEmbeddedId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ScheduleMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("heating");

                    b.Property<string>("SiteId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("DaikinInstallations");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.DaikinToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<string>("AccessTokenCiphertext")
                        .HasColumnType("text");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<string>("DaikinSubject")
                        .HasColumnType("text");

                    b.Property<int>("EncryptionVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("");

                    b.Property<string>("RefreshTokenCiphertext")
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("DaikinTokens");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.DhwCycle", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("ActualCost")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("ActualEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ActualStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("BackupHeaterUsed")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("EstimatedCompletionUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset?>("LastVerificationSampleUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PlannedStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PowerProfileJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal?>("PredictedCost")
                        .HasColumnType("numeric");

                    b.Property<int>("PredictedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("ReservedDurationMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ScheduleAcceptedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<double?>("StartTemperatureC")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset?>("TargetReachedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("TargetTemperatureC")
                        .HasColumnType("double precision");

                    b.Property<int>("TargetVerificationCount")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "PlannedStartUtc");

                    b.ToTable("DhwCycles");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.FlexibleScheduleState", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("LastComfortRunUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastEcoRunUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextScheduledComfortUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextScheduledEcoUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("FlexibleScheduleStates");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.HomeAssistantConnection", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("ControlEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ControlTokenCiphertext")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EncryptionVersion")
                        .HasColumnType("integer");

                    b.Property<string>("HeatingDeviationEntityId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("StaleAfterMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("TelemetryEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("TelemetryTokenCiphertext")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("HomeAssistantConnections");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.PriceSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("SavedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TodayPricesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TomorrowPricesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Zone", "Date");

                    b.ToTable("PriceSnapshots");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.ScheduleHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SchedulePayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ScheduleHistory");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.ThermalControlCommand", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Error")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<double?>("PreviousValue")
                        .HasColumnType("double precision");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<double?>("RequestedValue")
                        .HasColumnType("double precision");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TimestampUtc");

                    b.ToTable("ThermalControlCommands");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.ThermalControlState", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("CurrentDeviationC")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("CurrentPlanId")
                        .HasColumnType("uuid");

                    b.Property<string>("FallbackReason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("LastDeviationWriteUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastHeartbeatUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LeaseExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("ManualOverrideDeviationC")
                        .HasColumnType("double precision");

                    b.Property<string>("ManualOverrideReason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset?>("ManualOverrideUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("PiIntegral")
                        .HasColumnType("double precision");

                    b.HasKey("UserId");

                    b.ToTable("ThermalControlStates");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.ThermalEntityConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ExpectedUnit")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double?>("MaximumRatePerHour")
                        .HasColumnType("double precision");

                    b.Property<double?>("MaximumValid")
                        .HasColumnType("double precision");

                    b.Property<double?>("MinimumValid")
                        .HasColumnType("double precision");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "EntityId");

                    b.HasIndex("UserId", "Role")
                        .IsUnique();

                    b.ToTable("ThermalEntityConfigs");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.ThermalEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TimestampUtc");

                    b.ToTable("ThermalEvents");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.ThermalHourlyAggregate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double?>("AverageCop")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageLwtC")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageOutsideTemperatureC")
                        .HasColumnType("double precision");

                    b.Property<double?>("AverageRoomTemperatureC")
                        .HasColumnType("double precision");

                    b.Property<double>("HeatOutputKwh")
                        .HasColumnType("double precision");

                    b.Property<double>("HeatPumpEnergyKwh")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("HourUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RoomsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "HourUtc")
                        .IsUnique();

                    b.ToTable("ThermalHourlyAggregates");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.ThermalModelVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MetricsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ModelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("TrainingFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("TrainingToUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ModelType", "CreatedAtUtc");

                    b.ToTable("ThermalModelVersions");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.ThermalOptimizationJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Error")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTimeOffset?>("LeaseExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LeaseOwner")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PendingKey")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RequestJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("PendingKey")
                        .IsUnique();

                    b.HasIndex("UserId", "Status");

                    b.HasIndex("Status", "Priority", "CreatedAtUtc");

                    b.ToTable("ThermalOptimizationJobs");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.ThermalPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InputSnapshotJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("IsShadow")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("ObjectiveCost")
                        .HasColumnType("numeric");

                    b.Property<int>("SolverDurationMs")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("ValidFromUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ValidUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAtUtc");

                    b.ToTable("ThermalPlans");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.ThermalPlanStep", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<double>("Confidence")
                        .HasColumnType("double precision");

                    b.Property<string>("DecisionReasonJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double>("DesiredHeatOutputKw")
                        .HasColumnType("double precision");

                    b.Property<double>("DesiredLwtDeviationC")
                        .HasColumnType("double precision");

                    b.Property<string>("DhwMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("DhwReserved")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("EndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExpectedRoomsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<decimal>("IncrementalCost")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("StartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ThermalPlanId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ThermalPlanId", "StartUtc");

                    b.ToTable("ThermalPlanSteps");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.ThermalRoomConfig", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("IsCritical")
                        .HasColumnType("boolean");

                    b.Property<double>("MaximumRateCPerHour")
                        .HasColumnType("double precision");

                    b.Property<double>("MaximumValidC")
                        .HasColumnType("double precision");

                    b.Property<double>("MinimumValidC")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("TargetOffsetC")
                        .HasColumnType("double precision");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "EntityId")
                        .IsUnique();

                    b.ToTable("ThermalRoomConfigs");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.ThermalSiteConfig", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("ActiveDeviationLimitC")
                        .HasColumnType("double precision");

                    b.Property<double>("BaseRoomTargetC")
                        .HasColumnType("double precision");

                    b.Property<int>("ComfortFlexibilityDays")
                        .HasColumnType("integer");

                    b.Property<int>("ComfortIntervalDays")
                        .HasColumnType("integer");

                    b.Property<double>("ComfortSetpointC")
                        .HasColumnType("double precision");

                    b.Property<bool>("ComfortSetpointConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("ControlMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Legacy");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DhwLeaseExpiresUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DhwLeaseOwner")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("DhwWriter")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Legacy");

                    b.Property<bool>("HeatPumpPowerSignVerified")
                        .HasColumnType("boolean");

                    b.Property<double>("LowerComfortBandC")
                        .HasColumnType("double precision");

                    b.Property<string>("TariffDefinitionJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("TariffEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Europe/Stockholm");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("UpperComfortBandC")
                        .HasColumnType("double precision");

                    b.Property<string>("VariableCostComponentsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<bool>("WeatherCurveVerified")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.ToTable("ThermalSiteConfigs");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.ThermalTelemetrySample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool?>("BackupHeaterActive")
                        .HasColumnType("boolean");

                    b.Property<double?>("BrineInC")
                        .HasColumnType("double precision");

                    b.Property<double?>("BrineOutC")
                        .HasColumnType("double precision");

                    b.Property<double?>("Cop")
                        .HasColumnType("double precision");

                    b.Property<bool?>("DefrostActive")
                        .HasColumnType("boolean");

                    b.Property<bool?>("DhwActive")
                        .HasColumnType("boolean");

                    b.Property<double?>("FlowLitresPerMinute")
                        .HasColumnType("double precision");

                    b.Property<double?>("HeatOutputKw")
                        .HasColumnType("double precision");

                    b.Property<double?>("HeatPumpPowerKw")
                        .HasColumnType("double precision");

                    b.Property<double?>("LeavingWaterTemperatureC")
                        .HasColumnType("double precision");

                    b.Property<double?>("OutsideTemperatureC")
                        .HasColumnType("double precision");

                    b.Property<string>("OutsideTemperatureForecastJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double?>("PropertyPowerKw")
                        .HasColumnType("double precision");

                    b.Property<string>("QualityJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double?>("ReturnWaterTemperatureC")
                        .HasColumnType("double precision");

                    b.Property<string>("RoomTemperaturesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<double?>("SolarIrradianceWm2")
                        .HasColumnType("double precision");

                    b.Property<decimal?>("SpotPriceSekPerKwh")
                        .HasColumnType("numeric");

                    b.Property<double?>("TankTemperatureC")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double?>("WindSpeedMps")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "TimestampUtc")
                        .IsUnique();

                    b.ToTable("ThermalTelemetrySamples");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.UserAccount", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DaikinSubjectHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("LastLoginUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.HasIndex("DaikinSubjectHash")
                        .IsUnique();

                    b.ToTable("UserAccounts");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ExpiresAtUtc");

                    b.ToTable("UserSessions");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.UserSettings", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("AutoApplySchedule")
                        .HasColumnType("boolean");

                    b.Property<double>("ComfortEarlyPercentile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("double precision")
                        .HasDefaultValueSql("0.1");

                    b.Property<int>("ComfortFlexibilityDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(7);

                    b.Property<int>("ComfortHours")
                        .HasColumnType("integer");

                    b.Property<int>("ComfortIntervalDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(21);

                    b.Property<int>("EcoFlexibilityHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(12);

                    b.Property<int>("EcoIntervalHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(24);

                    b.Property<int>("MaxComfortGapHours")
                        .HasColumnType("integer");

                    b.Property<string>("SchedulingMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Classic");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("auto");

                    b.Property<double>("TurnOffPercentile")
                        .HasColumnType("double precision");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("SE3");

                    b.HasKey("UserId");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.ThermalPlanStep", b =>
                {
                    b.HasOne("Prisstyrning.Data.Entities.ThermalPlan", "ThermalPlan")
                        .WithMany("Steps")
                        .HasForeignKey("ThermalPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThermalPlan");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.ThermalPlan", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
