// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Prisstyrning.Data;

#nullable disable

namespace Prisstyrning.Data.Migrations
{
    [DbContext(typeof(PrisstyrningDbContext))]
    partial class PrisstyrningDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Prisstyrning.Data.Entities.AdminRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("HasHangfireAccess")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.HasKey("UserId");

                    b.ToTable("AdminRoles");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.DaikinToken", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("DaikinTokens");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.PriceSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("SavedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TodayPricesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("TomorrowPricesJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("Zone", "Date");

                    b.ToTable("PriceSnapshots");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.ScheduleHistoryEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SchedulePayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ScheduleHistory");
                });

            modelBuilder.Entity("Prisstyrning.Data.Entities.UserSettings", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("AutoApplySchedule")
                        .HasColumnType("boolean");

                    b.Property<int>("ComfortHours")
                        .HasColumnType("integer");

                    b.Property<int>("MaxComfortGapHours")
                        .HasColumnType("integer");

                    b.Property<double>("TurnOffPercentile")
                        .HasColumnType("double precision");

                    b.Property<string>("Zone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("SE3");

                    b.HasKey("UserId");

                    b.ToTable("UserSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
